### ISSUE TITLE
Integer Constraints

### ISSUE THREAD

**Issue by royvelich** [pnnl/L2O-pMINLP#2]
Hi,
Thanks for sharing the package.
I have a question. Is it possible to define an integer constraint based on continuous variables? For example, the difference between two continuous variables should be an integer.
If so, is there a simple coding example that shows how to do it?

Thanks :-)

**Comment by royvelich** [comment]
@drgona @LucasBoTang 
I hope you'll have a chance to look :-)

**Comment by LucasBoTang** [comment]
Hi @royvelich,

In mathematical programming, one way to force the difference between two continuous variables into an integer is to introduce an integer variable y as part of the model’s output and add the constraint x_1 - x_2 == y.

A similar approach can be applied to our package. Since we currently only support inequality constraints, you could have an output y, which is not in the objective function, and translate the equality constraint into two inequalities: x_1 - x_2 <= y and x_1 - x_2 >= y.

However, please note that this approach hasn't been extensively tested in our experiments, so the effectiveness of this workaround in practice is still uncertain.

Feel free to let us know if you have any more questions, and thank you again for using the package!

Best,
Bo
